def seed_products
  puts "Seeding products..."
  Product.create(code: '32PHS4112', definition: '"32"" HD READY DVBS2 LED TV"')
  Product.create(code: '32PHS4503', definition: '"32"" HD READY DVBS2 LED TV"')
  Product.create(code: '39PHS4112', definition: '"39""HD READY DVBS2 LED TV"')
  Product.create(code: '43PFS4112', definition: '43"FULL HD DVBS2 LED TV')
  Product.create(code: '43PFS5302', definition: '43"FULL HD DVBS2 SMART LED TV')
  Product.create(code: '43PFS5503', definition: '"43""FULL HD DVBS2  LED TV"')
  Product.create(code: '43PFS5803', definition: '43"FULL HD DVBS2 SMART LED TV')
  Product.create(code: '49PFS5302', definition: '49"FULL HD DVBS2 SMART LED TV')
  Product.create(code: '50PFS5803', definition: '50"FULL HD DVBS2 SMART LED TV')
  Product.create(code: '50PUS6162', definition: '50"ULTRA HD DVBS2 SMART LED TV')
  Product.create(code: '50PUS6503', definition: '50"ULTRA HD DVBS2 SMART LED TV')
  Product.create(code: '50PUS6704', definition: 'Philips 50"4K UHD Smart')
  Product.create(code: '75PUS7354', definition: 'Philips 4K Android TV')
  Product.create(code: 'ANK06001GR', definition: 'ANKASTRE AHŞAP MODÜL GRİ')
  Product.create(code: 'ANK06001WH', definition: 'ANKASTRE AHŞAP MODÜL BEYAZ')
  Product.create(code: 'ANK06002WH', definition: 'ANKASTRE AHŞAP MODÜL OPTI-WHITE')
  Product.create(code: 'ANK07001WH', definition: 'Ankastre Ahşap Bulaşık & Ocak Modülü')
  Product.create(code: 'B1ZMA18809', definition: 'Klima 18000 BTU dış')
  Product.create(code: 'B1ZMI18809', definition: 'Klima 18000 BTU iç')
  Product.create(code: 'BBH22454', definition: 'Kablosuz Dik Şarjlı Süpürge')
  Product.create(code: 'BBHMOVE4N', definition: 'Portatif küçük elektrikli süpürge')
  Product.create(code: 'BBZ41FGALL', definition: 'Elektrik süpürgesi toz torbası')
  Product.create(code: 'BCH3ALL21', definition: 'Dik Şarjlı Elektrik Süpürgesi')
  Product.create(code: 'BCH6ATH25', definition: 'Dik Şarjlı Elektrik Süpürgesi')
  Product.create(code: 'BCS612KA2', definition: 'Şarjlı dik süpürge')
  Product.create(code: 'BFL524MB0', definition: 'Ankastre mikrodalga')
  Product.create(code: 'BFL524MW0', definition: 'Ankastre mikrodalga')
  Product.create(code: 'BGB6SIL1', definition: 'Toz torbalı zemin tipi elektrikli süpürg')
  Product.create(code: 'BGB7230', definition: 'Toz Torbalı Elektrikli Süpürge')
  Product.create(code: 'BGB7330', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGBS4HYG1', definition: 'Toz torbalı zemin tipi elektrikli süpürg')
  Product.create(code: 'BGC1UB130', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGC2U230', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGC41Q69', definition: 'Toz torbasız elektrik süpürgesi')
  Product.create(code: 'BGL35MON6', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL3A230C', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL3A330C', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL4330', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL6POW1', definition: 'Toz torbalı zemin tipi elektrikli süpürg')
  Product.create(code: 'BGL8PERF5', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL8PERF7', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL8PRO1', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL8SIL59D', definition: 'Elektrikli süpürge')
  Product.create(code: 'BGL8ZOON', definition: 'Toz Torbalı Elektrikli Süpürge')
  Product.create(code: 'BGN2A111', definition: 'Toz Torbalı Elektrikli Süpürge')
  Product.create(code: 'BGS41PRO', definition: 'Toz torbasız elektrik süpürgesi')
  Product.create(code: 'BGS41X300', definition: 'Toz torbasız zemin tipi elektrikli süpür')
  Product.create(code: 'BGS4U232', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS4U332S', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS5330R', definition: 'Torbasız Elektrikli Süpürge')
  Product.create(code: 'BGS5PERF5', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS5SIL66C', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS6PRO4', definition: 'Toz torbasız elektrik süpürgesi')
  Product.create(code: 'BGS7PERF5', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS7POW1', definition: 'Toz torbasız zemin tipi elektrikli süpür')
  Product.create(code: 'BGS7RCL', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BGS7SIL64', definition: 'Elektrikli Süpürge')
  Product.create(code: 'BHN14090', definition: 'Şarjlı el süpürgesi')
  Product.create(code: 'BHN20110', definition: 'Şarjlı el süpürgesi')
  Product.create(code: 'BKS4043', definition: 'Şrj. el süp.')
  Product.create(code: 'BSG6A110', definition: 'Elektrikli süpürge')
  Product.create(code: 'BSG6B111', definition: 'Elektrikli süpürge')
  Product.create(code: 'BSGL3A210', definition: 'Elektrikli süpürge')
  Product.create(code: 'BSGL3A230', definition: 'Elektrikli süpürge')
  Product.create(code: 'DFT63CA20T', definition: 'Sürgülü Aspiratör 60 cm, Beyaz')
  Product.create(code: 'DFT63CA21T', definition: 'Sürgülü Aspiratör 60 cm, Beyaz')
  Product.create(code: 'DFT63CA50T', definition: 'Sürgülü Aspiratör 60 cm, Çelik')
  Product.create(code: 'DHI645FTR', definition: 'Sürgülü Aspiratör 60 cm, Çelik')
  Product.create(code: 'DHU632CTR', definition: 'Klasik Aspiratör, Beyaz')
  Product.create(code: 'DKE915A', definition: 'Davlumbaz')
  Product.create(code: 'DUL62MA20T', definition: 'Klasik Aspiratör, Beyaz')
  Product.create(code: 'DWA067A50T', definition: 'Davlumbaz')
  Product.create(code: 'DWA06E621', definition: 'Davlumbaz')
  Product.create(code: 'DWA06E651', definition: 'Davlumbaz')
  Product.create(code: 'DWA06E661', definition: 'Davlumbaz')
  Product.create(code: 'DWB064W21T', definition: 'Davlumbaz')
  Product.create(code: 'DWB064W51T', definition: 'Davlumbaz')
  Product.create(code: 'DWB06W452T', definition: 'Davlumbaz')
  Product.create(code: 'DWG66CD60T', definition: 'Davlumbaz')
  Product.create(code: 'DWK065G20T', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK065G60T', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK06G660', definition: 'Davlumbaz')
  Product.create(code: 'DWK095G20T', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK095G60T', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK65AD20R', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK65AD60R', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK65AD70R', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWK66AJ70T', definition: 'eğimli davlumbaz')
  Product.create(code: 'DWP64CC20T', definition: 'Davlumbaz')
  Product.create(code: 'DWP64CC50T', definition: 'Davlumbaz')
  Product.create(code: 'DWP64CC60T', definition: 'Davlumbaz')
  Product.create(code: 'GCM15VW20N', definition: 'Sandık dondurucu')
  Product.create(code: 'GCM23VW20N', definition: 'Sandık dondurucu')
  Product.create(code: 'GCM24AW20N', definition: 'Sandık dondurucu')
  Product.create(code: 'GCM28VW20N', definition: 'Sandık dondurucu')
  Product.create(code: 'GCM34AW20N', definition: 'Sandık Dondurucu')
  Product.create(code: 'GFN7905', definition: 'Vantilatör')
  Product.create(code: 'GM7921', definition: 'ESEN VANTILATOR')
  Product.create(code: 'GM7922', definition: 'KUTUP VANTILATOR')
  Product.create(code: 'GM7924', definition: 'ALASKA VANTILATOR')
  Product.create(code: 'GSN36AI31', definition: 'Solo dondurucu')
  Product.create(code: 'GSV24VW20N', definition: 'Solo dondurucu')
  Product.create(code: 'GSV24VW31N', definition: 'Solo dondurucu')
  Product.create(code: 'GSV29VW31N', definition: 'Solo dondurucu')
  Product.create(code: 'GSV33VW31N', definition: 'Solo dondurucu')
  Product.create(code: 'GTV15NW30N', definition: 'Tezgah üstü dondurucu')
  Product.create(code: 'HBF010BR1T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF234EB0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BA0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BB0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BH0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BR0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BV0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF514BW0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF534EB0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF534ES0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBF534EW0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBG43S320Q', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBG43S350Q', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBG43S360Q', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBG635BS1', definition: 'Fırın')
  Product.create(code: 'HBG655NB1', definition: 'Fırın')
  Product.create(code: 'HBG655NW1', definition: 'Fırın')
  Product.create(code: 'HBJ558YB0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBJ558YS0T', definition: 'Ankastre Fırın')
  Product.create(code: 'HBJ558YW0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN301E2T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN301E6T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN331E2T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN331S2T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN331W0T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN551E1T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN559E1T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN559E3T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN559S3T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HBN559W3T', definition: 'Ankastre elektrikli fırın')
  Product.create(code: 'HDSP3', definition: 'Itech HDSP2 Hdmi dagitici')
  Product.create(code: 'HGD525120T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD595120T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD645220T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD695220T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD69W250T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD745360T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD74W350T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD74X455T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD79W220T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HGD79W320T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'HKP110120', definition: 'Midi Fırın, Beyza')
  Product.create(code: 'HMT72G420', definition: 'Izgaralı Mikrodalga Fırın')
  Product.create(code: 'HMT72G450', definition: 'Izgaralı Mikrodalga Fırın')
  Product.create(code: 'HMT75G654', definition: 'Izgaralı Ankastre Mikrodalga Fırın')
  Product.create(code: 'HMT75M624', definition: 'Ankastre Mikrodalga')
  Product.create(code: 'HMT75M651', definition: 'Ankastre Mikrodalga')
  Product.create(code: 'HMT75M664', definition: 'Ankastre Mikrodalga')
  Product.create(code: 'HMT84G421', definition: 'Izgaralı Mikrodalga Fırın')
  Product.create(code: 'HMT84G451', definition: 'Izgaralı Mikrodalga Fırın')
  Product.create(code: 'HTB12E428T', definition: 'Midi Fırın, Beyaz')
  Product.create(code: 'HTB12E458T', definition: 'Midi Fırın, Gümüş')
  Product.create(code: 'HXR390H29T', definition: 'Solo gaz kombinasyonlu fırın')
  Product.create(code: 'KAN90VI20N', definition: 'Soğutucu-dondurucu kombinasyonu SBS')
  Product.create(code: 'KDN28NW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN53NL20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN53NL22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN53NW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN53NW22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN53NW23N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN55N1F0N', definition: 'Solo buzdolabı')
  Product.create(code: 'KDN55NWF0N', definition: 'Solo buzdolabı')
  Product.create(code: 'KDN56AW32N', definition: 'Solo soğutma otomatı')
  Product.create(code: 'KDN56AWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56NI22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56NW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56NW22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56PI32N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56PW32N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56VI33N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56VI35N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56VW23N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56VW25N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56XIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN56XWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN59AW35N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN64VL21N', definition: 'Solo çift kapılı soğutucu-dondurucu üst')
  Product.create(code: 'KDN64VW20N', definition: 'Solo çift kapılı soğutucu-dondurucu üst')
  Product.create(code: 'KDN65VW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN74AF20N', definition: 'Solo çift kapılı soğutucu-dondurucu üst')
  Product.create(code: 'KDN74AL21N', definition: 'Solo çift kapılı soğutucu-dondurucu üst')
  Product.create(code: 'KDN74AW20N', definition: 'Solo çift kapılı soğutucu-dondurucu üst')
  Product.create(code: 'KDN75VW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN76AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN76AWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN86AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDN86AWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDV47VW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDV58VL30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KDV58VW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGA76PIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGB86AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGE58AW41N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGE58BI44N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGE58DL30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGE58DW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56AB30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56ABF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56AI30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56AI32N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56AW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56HI40N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56IJ3AN', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56LB30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56LBF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56LW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56LWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56PI30N', definition: 'Solo sogutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56PI32N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56PW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56PW32N ', definition: 'No-frost Buzdolabı')
  Product.create(code: 'KGN56UW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56VI30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56VL30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN56VW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57AW25N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57PI26N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57PW22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57PW23N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57VI20N', definition: 'Solo çift kapılı soğutucu-dondurucu alt')
  Product.create(code: 'KGN57VI22N', definition: 'Solo çift kapılı soğutucu-dondurucu alt')
  Product.create(code: 'KGN57VW20N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN57VW22N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76AI30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76AI32', definition: 'Buzdolabı')
  Product.create(code: 'KGN76AI32N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76AW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76AWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76DI30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76DW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76VIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN76VWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AI30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AI40N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AI42N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AIF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86AWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86DW30N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGN86DWF0N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KGV58VW31N', definition: 'Solo soğutucu-dondurucu kombinasyonu')
  Product.create(code: 'KSZ1CVR00', definition: 'Kapı')
  Product.create(code: 'LE106S2FMD', definition: '"42"" FULL HD DVBS2 LED TV"')
  Product.create(code: 'LE124S1FMD', definition: '"49"" FULL HD DVBS2 LED TV"')
  Product.create(code: 'LE127S15SM', definition: '"50"" FULL HD LED SMART MONİTÖR"')
  Product.create(code: 'LE82S18HM', definition: '"32"" HD READY LED MONİTÖR"')
  Product.create(code: 'LE82S1HMD', definition: '"32"" HD READY DVBS2 LED TV"')
  Product.create(code: 'MCM3501M', definition: 'Mutfak robotu')
  Product.create(code: 'MCM4000', definition: 'Mutfak robotu')
  Product.create(code: 'MCP3500', definition: 'Narenciye sıkacağı')
  Product.create(code: 'MCP72GMB', definition: 'Narenciye suyu sıkma cihazı')
  Product.create(code: 'MES25A0', definition: 'Katı Meyve Sıkacağı')
  Product.create(code: 'MES3500', definition: 'Katı Meyve Sıkacağı')
  Product.create(code: 'MES4010', definition: 'Katı Meyve Sıkacağı')
  Product.create(code: 'MFQ24200', definition: 'El mikseri')
  Product.create(code: 'MFQ2420B', definition: 'El mikseri')
  Product.create(code: 'MFQ3030', definition: 'El mikseri')
  Product.create(code: 'MFQ36300', definition: 'El mikseri')
  Product.create(code: 'MFQ36300D', definition: 'El mikseri')
  Product.create(code: 'MFQ36300Y', definition: 'El mikseri')
  Product.create(code: 'MFQ36460', definition: 'Stantlı El Mikseri')
  Product.create(code: 'MFQ40303', definition: 'El mikseri')
  Product.create(code: 'MFQ4030K', definition: 'El mikseri')
  Product.create(code: 'MFQ4080', definition: 'El mikseri seti')
  Product.create(code: 'MFQP1000', definition: 'El mikseri')
  Product.create(code: 'MFW3520W', definition: 'Kıyma Makinesi')
  Product.create(code: 'MFW45020', definition: 'Kıyma Makinesi')
  Product.create(code: 'MFW67440', definition: 'Kıyma Makinesi')
  Product.create(code: 'MKM6000', definition: 'Kahve Değirmeni')
  Product.create(code: 'MKM6003', definition: 'Kahve Değirmeni')
  Product.create(code: 'MMB65G5M', definition: 'SilentMixx Blender')
  Product.create(code: 'MMBP1000', definition: 'Sabit mikserler')
  Product.create(code: 'MMR08A1', definition: 'Üniversal doğrayıcı')
  Product.create(code: 'MMR08R2', definition: 'Üniversal doğrayıcı')
  Product.create(code: 'MMR15A1', definition: 'Üniversal doğrayıcı')
  Product.create(code: 'MMRP1000', definition: 'Üniversal doğrayıcı')
  Product.create(code: 'MS62B6190', definition: 'Ergomixx El Blender Seti')
  Product.create(code: 'MS6CB6110', definition: 'Uzun mikser')
  Product.create(code: 'MSM2410K', definition: 'El Blenderı')
  Product.create(code: 'MSM64010', definition: 'El Blenderı')
  Product.create(code: 'MSM64110', definition: 'El Blenderı')
  Product.create(code: 'MSM66110D', definition: 'El Blenderı')
  Product.create(code: 'MSM66110Y', definition: 'El Blenderı')
  Product.create(code: 'MSM66150', definition: 'El Blender Seti')
  Product.create(code: 'MSM66155', definition: 'El Blender Seti')
  Product.create(code: 'MSM67170', definition: 'El Blender Seti')
  Product.create(code: 'MSM87140', definition: 'El Blender Seti')
  Product.create(code: 'MSMP1000', definition: 'EL BLENDERÝ,')
  Product.create(code: 'MUC88B68TR', definition: 'Çok fonksiyonlu profesyonel pişirici')
  Product.create(code: 'MUM44R1', definition: 'Mutfak Makinesi')
  Product.create(code: 'MUM54D00', definition: 'Mutfak Makinesi')
  Product.create(code: 'MUM54P00', definition: 'Mutfak Makinesi')
  Product.create(code: 'MUM58020', definition: 'Mutfak Şefi')
  Product.create(code: 'MUM58720', definition: 'CreationLine Mutfak Makinesi')
  Product.create(code: 'MUMP1000', definition: 'Mutfak robotu')
  Product.create(code: 'MX915ECR', definition: 'Verifone POS Entegre Yazarkasa')
  Product.create(code: 'NR1010', definition: 'ÜTÜ MASASI')
  Product.create(code: 'NR1013', definition: 'ÜTÜ MASASI')
  Product.create(code: 'PBH6C5B60O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PBP0C2B80L', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'PBP0C2B80O', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'PBP0C5B80O', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'PBP6C2B80O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PBP6C5B60O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PBP6C5B80O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PBP6C6B80O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PBT900', definition: 'Yazarkasa')
  Product.create(code: 'PBY6C5B80O', definition: 'Karışık ocak')
  Product.create(code: 'PCP675B21E', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PCP6A5B80', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PGP6B5B60O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PHC5363', definition: 'Bukle şekillendirici')
  Product.create(code: 'PHD5767', definition: 'Saç kurutma makinesi')
  Product.create(code: 'PHD5781', definition: 'Saç kurutma makinesi')
  Product.create(code: 'PHD5987', definition: 'Saç kurutma makinesi')
  Product.create(code: 'PHD7961', definition: 'Saç kurutma makinesi')
  Product.create(code: 'PHD9760', definition: 'Saç kurutma makinesi')
  Product.create(code: 'PHS5263', definition: 'Saç düzleştirici')
  Product.create(code: 'PHS5947', definition: 'Saç düzleştirici')
  Product.create(code: 'PHS7961', definition: 'Saç düzleştirici')
  Product.create(code: 'PHS9460', definition: 'Saç düzleştirici')
  Product.create(code: 'PKE611D17E', definition: 'Elektrikli ocak')
  Product.create(code: 'PNH6B6B10O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PNP6B6B80O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POH6C6B11O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP0C2B10L', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'POP0C2B10O', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'POP0C6B10L', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'POP0C6B10O', definition: 'Kendinden kumandalı, gazlı solo ocak')
  Product.create(code: 'POP6C2B11O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP6C6B11O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP6C6B81O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP6C9O00O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP7C2O10O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP7C6O10O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'POP7C9O10O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPH6A6B20', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPH6A6B20L', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPP6A2B20O', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPQ7A6B10', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPQ7A6B20', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPQ7A8B90', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPS9A6B90', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'PPW3301', definition: 'Banyo tartısı')
  Product.create(code: 'PPW3330', definition: 'Ynsanlar için kullanylan tarty')
  Product.create(code: 'PRP6A6D70', definition: 'Kendinden kumandalı, gazlı ankastre ocak')
  Product.create(code: 'Q8AANKSINS', definition: 'PROM.BOSCH ANK 250')
  Product.create(code: 'Q8ABKEAINS', definition: 'Prom.Insert 1pk.(20 adet)')
  Product.create(code: 'Q8AKEAPST1', definition: 'BEZ CANTA')
  Product.create(code: 'Q8ASOLOINS', definition: 'BOSCH SOLO FL')
  Product.create(code: 'Q8BQUANTUM', definition: 'Finish Quantum')
  Product.create(code: 'RDG5014TR', definition: 'LED\'li Termosifon, 50 lt.')
  Product.create(code: 'RDG5024TR', definition: 'LED\'li Termosifon, 50 lt.')
  Product.create(code: 'RDG6514TR', definition: 'LED\'li Termosifon, 65 lt.')
  Product.create(code: 'RDG6515TR', definition: 'LCD Ekranlı Termosifon, 65 Lt.')
  Product.create(code: 'RDG6524TR', definition: 'LED\'li Termosifon, 65 lt.')
  Product.create(code: 'RDG8024TR', definition: 'LED\'li Termosifon, 80 Lt.')
  Product.create(code: 'RDW1570', definition: 'Su Sebili')
  Product.create(code: 'RDW1571', definition: 'Su Sebili')
  Product.create(code: 'RDW1572', definition: 'Su Sebili')
  Product.create(code: 'SMI25DB00T', definition: 'Entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SMI45IS00T', definition: 'Entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SMI50D02TR', definition: 'Entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SMI53M05TR', definition: 'Ankastre bulaşık makinesi')
  Product.create(code: 'SMI68L05TR', definition: 'Entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SMILPLAYER', definition: 'ANDROID MEDIA BOX')
  Product.create(code: 'SMS20D02TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS22BW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS23BA00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS23BW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS23DW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS30E02TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS30E09TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS43D08TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS43D12TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS44DI00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS44DW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS45JI00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS45JW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS45NI00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS45NW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS46II00T', definition: 'solo bulaşık yıkama makinesi')
  Product.create(code: 'SMS46IW00T', definition: 'solo bulaşık yıkama makinesi')
  Product.create(code: 'SMS46JI00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS46JI01T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS46JW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS46JW01T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS46MB00T', definition: 'solo bulaşık yıkama makinesi')
  Product.create(code: 'SMS46NB00T', definition: 'solo bulaşık yıkama makinesi')
  Product.create(code: 'SMS48D02TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS53L12TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS53L18TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS63L06TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS67MW00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS67NI00T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS67NI01T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS67NW01T', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS68L22TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS68L28TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS68N80TR', definition: 'solo bulaşık yıkama makinesi')
  Product.create(code: 'SMS73L02TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMS73L08TR', definition: 'Solo bulaşık makinesi')
  Product.create(code: 'SMU63L05TR', definition: 'Tezgah alti bulasik makinesi')
  Product.create(code: 'SMU63M15TR', definition: 'Tezgah altı bulaşık makinesi')
  Product.create(code: 'SMV26MX00T', definition: 'Tam entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SMV40D06TR', definition: 'Tam entegre edilmiş bulaşık makinesi')
  Product.create(code: 'SN32DKA005', definition: 'Sunny TV')
  Product.create(code: 'SN40DAB005', definition: 'Sunny TV')
  Product.create(code: 'SN49DLK023', definition: 'Sunny TV')
  Product.create(code: 'SN55L8400', definition: 'Sunny TV')
  Product.create(code: 'SNO24LED033', definition: 'Sunny TV')
  Product.create(code: 'TAT6A004', definition: 'Ekmek kızartma makinesi')
  Product.create(code: 'TAT6A111', definition: 'Kompakt tost makinesi')
  Product.create(code: 'TAT6A113', definition: 'Kompakt tost makinesi')
  Product.create(code: 'TAT6A114', definition: 'Kompakt tost makinesi')
  Product.create(code: 'TAT6A803', definition: 'Ekmek kızartma makinesi')
  Product.create(code: 'TAT6A913', definition: 'Ekmek kızartma makinesi')
  Product.create(code: 'TAT8612', definition: 'Ekmek kızartma makinesi')
  Product.create(code: 'TDA3024010', definition: 'Buharlı ütü')
  Product.create(code: 'TDA3026110', definition: 'Buharlı ütü')
  Product.create(code: 'TDA5024010', definition: 'Buharlı ütü')
  Product.create(code: 'TDA5028110', definition: 'Buharlı ütü')
  Product.create(code: 'TDA703021A', definition: 'Buharlı ütü')
  Product.create(code: 'TDI903231A', definition: 'Buhar Motorlu Ütü')
  Product.create(code: 'TDI953222V', definition: 'Buhar Motorlu Ütü')
  Product.create(code: 'TDS2140', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS383112H', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS38311TR', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS4070', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS6010', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS6080TR', definition: 'Buhar istasyonu')
  Product.create(code: 'TDS8080TR', definition: 'Buhar istasyonu')
  Product.create(code: 'TFB4402V', definition: 'Tost makinesi')
  Product.create(code: 'TFB4431V', definition: 'Tost makinesi')
  Product.create(code: 'TKA3A031', definition: 'Filtre kahve makinesi')
  Product.create(code: 'TKA6A043', definition: 'Filtre kahve makinesi')
  Product.create(code: 'TKA6A044', definition: 'Filtre kahve makinesi')
  Product.create(code: 'TKM3003', definition: 'Coffeexx Türk Kahvesi Makinesi')
  Product.create(code: 'TKM6003', definition: 'Coffeexx Plus Türk Kahvesi Makinesi')
  Product.create(code: 'TRM1080V2', definition: 'Itech TRM1080V2 Transmiter')
  Product.create(code: 'TTA2010', definition: 'Çay makinesi')
  Product.create(code: 'TTA2201', definition: 'Çay makinesi')
  Product.create(code: 'TTA5603', definition: 'Çay makinesi')
  Product.create(code: 'TTA5883', definition: 'Çay makinesi')
  Product.create(code: 'TWK1201N', definition: 'Su ısıtıcı')
  Product.create(code: 'TWK3A011', definition: 'Plastik su ısıtıcı')
  Product.create(code: 'TWK6A011', definition: 'Su ısıtıcı')
  Product.create(code: 'TWK6A013', definition: 'Su ısıtıcı')
  Product.create(code: 'TWK6A014', definition: 'Su ısıtıcı')
  Product.create(code: 'TWK70A03', definition: 'Su Isıtıcı')
  Product.create(code: 'TWK7101', definition: 'Paslanmaz çelikten su kaynatma makinesi')
  Product.create(code: 'TWK7801', definition: 'Paslanmaz çelikten su kaynatma makinesi')
  Product.create(code: 'TWK7805', definition: 'Paslanmaz çelikten su kaynatma makinesi')
  Product.create(code: 'TWK8612P', definition: 'Su ısıtıcı')
  Product.create(code: 'TWK8613P', definition: 'Su ısıtıcı')
  Product.create(code: 'TX40DS503E', definition: '"40""  FULL HD LED TV"')
  Product.create(code: 'TX49DS503E', definition: '"49"" FULL HD LED TV"')
  Product.create(code: 'WAB12061TR', definition: 'Çamaşır makinesi')
  Product.create(code: 'WAB16061TR', definition: 'Çamasir makinesi')
  Product.create(code: 'WAB20264TR', definition: 'Çamaşır makinesi')
  Product.create(code: 'WAJ20170TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAJ20180TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAK20202TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAK20211TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAK2022STR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAK20260TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT20480TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24440TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24460TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24461TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24480TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT2448STR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24581TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24780TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT24S80TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT28460TR', definition: 'Tam otomatik çamasir Makinesi')
  Product.create(code: 'WAT28480TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT2849XTR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT28581TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT28682TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAT28780TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAW28560TR', definition: 'Çamaşır makinesi')
  Product.create(code: 'WAW2856XTR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAX28M80TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAX28M8XTR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAY287X3TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAY28862TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WAY288H0TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WDU28560TR', definition: 'Çamaþýr yýkama kurutma makinesi')
  Product.create(code: 'WGA141X0TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WGA142X0TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WGA142XVTR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WGA252X0TR', definition: 'Tam otomatik çamaşır Makinesi')
  Product.create(code: 'WNA254X0TR', definition: 'Çamaþýr yýkama kurutma makinesi')
  Product.create(code: 'WTB86202TR', definition: 'Çam.Kur.Mak.Bacasız')
  Product.create(code: 'WTE84101TR', definition: 'çamaşır kurutma makinesi')
  Product.create(code: 'WTH85200TR', definition: 'Çama?yr kurutma makinesi')
  Product.create(code: 'WTR85V00TR', definition: 'Çamaþýr kurutma makinesi')
  Product.create(code: 'WTW85461TR', definition: 'Çamaşır kurutma makinesi')
  Product.create(code: 'WTW8546XTR', definition: 'Çama?yr kurutma makinesi')
  Product.create(code: 'WTW85561TR', definition: 'Çamaşır kurutma makinesi')
  Product.create(code: 'WTY87760TR', definition: 'Çamaşır kurutma makinesi')
  Product.create(code: 'WTY88860TR', definition: 'Çamaşır kurutma makinesi')
  Product.create(code: 'WVG30460TR', definition: 'Çama?yr yykama kurutma makinesi')
  puts "Seeding products done."
end
